export const SEND_DOCUMENTS_ERROR = 'documents/SEND_DOCUMENTS_ERROR';
export const SEND_DOCUMENTS_FETCH = 'documents/SEND_DOCUMENTS_FETCH';
export const SEND_DOCUMENTS_DATA = 'documents/SEND_DOCUMENTS_DATA';
export const FETCH_DOCUMENTS_ERROR = 'documents/FETCH_DOCUMENTS_ERROR';
export const FETCH_DOCUMENTS_FETCH = 'documents/FETCH_DOCUMENTS_FETCH';
export const FETCH_DOCUMENTS_DATA = 'documents/FETCH_DOCUMENTS_DATA';

